#pragma once


#define I2C1_SCL_PIN  GP27 
#define I2C1_SDA_PIN  GP26 




#define USE_SERIAL
#define EE_HANDS

#define WS2812_DI_PIN GP10
#define RGBLIGHT_LED_COUNT 50
#define RGBLED_SPLIT {25, 25}
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_TWINKLE


#define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"

